languages = {
    "en":"Search Wikipedia",
    "ceb":"Pangitaa Wikipedia",
    "de":"Wikipedia durchsuchen",
    "fr":"Rechercher sur Wikipédia",
    "sv":"Sök på Wikipedia",
    "nl":"Doorzoek Wikipedia",
    "ru":"Искать в Википедии",
    "es":"Buscar en Wikipedia",
    "it":"Cerca in Wikipedia",
    "pl":"Przeszukaj Wikipedię",
    "arz":"تدوير ويكيبيديا",
    "zh":"搜索维基百科",
    "ja":"Wikipedia内を検索",
    "uk":"Пошук у Вікіпедії",
    "vi":"Tìm kiếm trên Wikipedia",
    "war":"Bilnga ha Wikipedia",
    "ar":"ابحث في ويكيبيديا",
    "pt":"Pesquisar na Wikipédia",
    "fa":"جستجو در ویکی‌پدیا",
    "ca":"Cerca a Viquipèdia",
    "id":"Telusuri Wikipedia",
    "sr":"Претражите Википедију",
    "ko":"위키백과 검색",
    "no":"Søk i Wikipedia",
    "tr":"Vikipedi üzerinde ara",
    "ce":"Википеди чохь лаха",
    "fi":"Hae Wikipediasta",
    "cs":"Hledat na Wikipedii",
    "hu":"Keresés a Wikipédián",
    "tt":"Wikipedia эчендә эзләү",
    "ro":"Căutare în Wikipedia",
    "sh":"Pretražite Wikipediju",
    "eu":"Wikipedia wikian bilatu",
    "nan":"Tī Wikipedia chhoē",
    "ms":"Cari Wikipedia",
    "he":"חיפוש בוויקיפדיה",
    "eo":"Serĉi tra Vikipedio",
    "hy":"Որոնել Վիքիպեդիա կայքում",
    "da":"Søg på Wikipedia",
    "bg":"Търсене в Уикипедия",
    "uz":"Vikipediyadan qidirish",
    "cy":"Chwilio Wicipedia",
    "sk":"Hľadať na Wikipédia",
    "et":"Otsi Vikipeediast",
    "be":"Шукаць у Вікіпедыі",
    "azb":"ویکی‌پدیا-دا آختار",
    "el":"Αναζήτηση σε Βικιπαίδεια",
    "kk":"Уикипедия жобасынан іздеу",
    "min":"Cari Wikipedia",
    "hr":"Pretraži projekt Wikipedija",
    "lt":"Ieškoti Vikipedijoje",
    "gl":"Procurar en Wikipedia",
    "ur":"ویکیپیڈیا میں تلاش کریں",
    "az":"Vikipediyada axtar",
    "sl":"Iskanje v Wikipediji",
    "lld":"Chir te Wikipedia",
    "ka":"ძიება ვიკიპედია",
    "nn":"Søk i Wikipedia",
    "ta":"விக்கிப்பீடியா தளத்தில் தேடு",
    "th":"ค้นหาใน วิกิพีเดีย",
    "hi":"विकिपीडिया में खोजें",
    "bn":"উইকিপিডিয়া অনুসন্ধান",
    "mk":"Пребарајте по Википедија",
    "yue":"搵維基百科",
    "la":"Quaerere apud Vicipaediam",
    "ast":"Buscar en Wikipedia",
    "lv":"Meklēt Vikipēdijā",
    "af":"Deursoek Wikipedia",
    "tg":"Ҷустуҷӯ дар Википедиа",
    "my":"ဝီကီပီးဒီးယား တွင် ရှာဖွေရန်",
    "te":"వికీపీడియా‌లో వెతకండి",
    "sq":"Kërko te Wikipedia",
    "mg":"Hikaroka eto amin&#039;i Wikipedia",
    "mr":"शोधा विकिपीडिया",
    "bs":"Pretraži Wikipediju",
    "oc":"Recercar sus Wikipèdia",
    "be-tarask":"Пошук у Вікіпэдыі",
    "br":"Klask e Wikipedia",
    "ml":"വിക്കിപീഡിയ സംരംഭത്തിൽ തിരയുക",
    "nds":"Söken Wikipedia",
    "ku":"Li ser Wîkîpediyayê bigere",
    "sw":"Tafuta Wikipedia",
    "ky":"Издөө",
    "lmo":"Cerca in Wikipedia",
    "jv":"Golèk ing Wikipédia",
    "pnb":"وکیپیڈیا وچ کھوجو",
    "new":"Search Wikipedia",
    "ckb":"لە ویکیپیدیادا بگەڕێ",
    "ht":"Chèche nan Wikipedya",
    "vec":"Serca drento de Wikipedia",
    "pms":"Sërca an Wikipedia",
    "lb":"Op Wikipedia sichen",
    "ba":"Википедия эсендә эҙләү",
    "su":"Paluruh Wikipedia",
    "ga":"Cuardaigh Vicipéid",
    "is":"Leita á Wikipedia",
    "szl":"Szukej we Wikipedia",
    "cv":"Википеди сайтра шыра",
    "pa":"ਵਿਕੀਪੀਡੀਆ ਖੋਜੋ",
    "fy":"Wikipedy trochsykje",
    "io":"Serchez en Wikipedio",
    "ha":"Ku bincika cikin Hausa Wikipedia",
    "tl":"Maghanap sa Wikipedia",
    "an":"Mirar en Wikipedia",
    "wuu":"搜寻维基百科",
    "mzn":"ویکی‌پدیا چرخه‌تو",
    "diq":"Wikipedia de cı geyre",
    "vo":"Sukön in Vükiped",
    "ig":"Chọọ na Wikipedia",
    "sco":"Sairch Wikipedia",
    "yo":"Ṣ&#039;àwáàrí nínú Wikipedia",
    "kn":"ವಿಕಿಪೀಡಿಯ ಅನ್ನು ಹುಡುಕಿ",
    "ne":"विकिपिडियामा खोज्नुहोस्",
    "gsw":"Search Wikimedia Incubator",
    "gu":"વિકિપીડિયા શોધો",
    "ia":"Cercar in Wikipedia",
    "avk":"Va Wikipedia betar",
    "crh":"Vikipediya içinde qıdır",
    "bar":"Suach (af Boarisch oda Deutsch)",
    "scn":"Risciduta",
    "ban":"Rereh ring Wikipédia",
    "bpy":"বিসারা উইকিপিডিয়া",
    "mn":"Википедиагаас хайх",
    "qu":"Maskay",
    "nv":"bíkanítá",
    "xmf":"გორუა ვიკიპედიას",
    "si":"විකිපීඩියා හොයන්න",
    "ps":"ويکيپېډيا پلټل",
    "frr":"Schük uun Wikipedia",
    "os":"Википедийы агурын",
    "tum":"Fufuza Wikipedia",
    "or":"ଉଇକିପିଡ଼ିଆରେ ଖୋଜିବେ",
    "sd":"وڪيپيڊيا ۾ ڳوليو",
    "bcl":"Maghanap sa Wikipedia",
    "sgs":"Ėiškuotė svetainie &quot;Wikipedia&quot;",
    "sah":"Бикипиэдьийэ иһигэр көрдөөһүн",
    "cdo":"Tō̤ Wikipedia",
    "gd":"Lorg air Uicipeid",
    "bug":"Telusuri Wikipedia",
    "yi":"זוכן װיקיפּעדיע",
    "ilo":"Agbiruk iti Wikipedia",
    "am":"ውክፔዲያ ውስጥ ፈልግ",
    "li":"Doorzeuk Wikipedia",
    "nap":"Truove dinto Wikipedia",
    "gor":"Lolohe Wikipedia",
    "mai":"विकिपिडियामे खोजी",
    "fo":"Leita í Wikipedia",
    "hsb":"Wikipedija přepytać",
    "shn":"ၶူၼ်ႉႁႃ ဝီႇၶီႇၽီးတီးယႃး",
    "as":"অসমীয়া ৱিকিপিডিয়াত সন্ধান কৰক",
    "lzh":"尋於維基大典",
    "egl":"Search Wikimedia Incubator",
    "ace":"Mita lam Wikipedia",
    "ie":"Serchar in Wikipedia",
    "wa":"Cweri so Wikipedia",
    "sa":"विकिपीडिया अन्विष्यताम्",
    "hyw":"Որոնել Ուիքիփետիա կայքին մէջ",
    "sat":"ᱥᱮᱸᱫᱽᱨᱟ ᱣᱤᱠᱤᱯᱤᱰᱤᱭᱟ",
    "zu":"bheka Wikipedia",
    "sn":"Tsvaga Wikipedia",
    "mhr":"Википедий сайтыште кычалаш",
    "lij":"Çèrca inte Wikipedia",
    "hif":"Wikipedia me khojo",
    "glk":"Wikipedia مئن وامج",
    "bjn":"Gagai Wikipidia",
    "km":"ស្វែងរក​ក្នុងវិគីភីឌា",
    "mrj":"Википеди сайтышты кӹчӓлӓш",
    "mni":"ꯊꯤꯔꯣ",
    "hak":"Chhìm",
    "ary":"قلّب ف ويكيپيديا",
    "dag":"Vihimi Dagbani Wikipedia",
    "pam":"Search Wikipedia",
    "rue":"Глядати Вікіпедія",
    "bh":"विकिपीडिया में खोजीं",
    "nso":"Fetleka  Wikipedia",
    "co":"Circà in Wikipedia",
    "so":"Raadi",
    "vls":"Doorzoek Wikipedia",
    "mi":"Search Wikipedia",
    "nds-NL":"Wikipedia döärsöken",
    "tly":"Bynəv Vikipediá",
    "se":"Oza Wikipedia:s",
    "myv":"Вешнемс Википедиясь-стэ",
    "kaa":"Wikipedia saytınan izlew",
    "rw":"Shakisha Wikipedia",
    "sc":"Chirca in intro de Wikipedia",
    "bo":"འཚོལ། Wikipedia",
    "kw":"Hwilas yn Wikipedia",
    "vep":"Eci Vikipedii",
    "tk":"Wikipediýa gözläň",
    "kab":"Nadi Wikipedia",
    "gv":"Ronsaghey",
    "mt":"Fittex fis-sit: Wikipedija",
    "gan":"尋下 維基百科",
    "vro":"Otsminõ Wikipedia",
    "mdf":"Вешендемс Википедиесь",
    "zea":"Zoek",
    "ab":"Асаит Авикипедиа аҟны аԥшаара",
    "ug":"Wikipedia ئىزدەش",
    "skr":"ڳولو",
    "smn":"Uusâ Wikipedia:st",
    "gn":"Eheka Vikipetã rendápe",
    "frp":"Rechèrchiér sus Vouiquipèdia",
    "pcd":"Tracher Wikipedia",
    "udm":"Википедия утчано",
    "kv":"Корсьны Wikipediaысь",
    "csb":"Szëkba",
    "ks":"وِکیٖپیٖڈیا مَنٛز کٔرِو تَلاش",
    "ay":"Buscar en Wikipedia",
    "nrf":"Rechercher sur Wikipedia",
    "ang":"Sec Wikipǣdia",
    "olo":"Eči Wikipedii",
    "lez":"Википедия жагъурун",
    "fur":"Cîr in Vichipedie",
    "lfn":"Xerca en Vicipedia",
    "nah":"Xiktemo ika Huiquipedia",
    "mwl":"Percurar an Biquipédia",
    "pap":"Búskeda di Wikipedia",
    "tw":"Hwehwɛ Wikipedia",
    "stq":"Wikipedia truchsäike",
    "ln":"Boluki Wikipedia",
    "lo":"ຊອກຫາ ວິກິພີເດຍ",
    "rm":"Tschertgar Wikipedia",
    "ext":"Precural Güiquipeya",
    "lad":"Buxca en la Vikipedya",
    "ff":"Yiylo e Wikipedia",
    "gom":"विकिपीडिया सोद",
    "dty":"विकिपिडिया खोजऽ",
    "av":"Wikipedia сайталда балагьизе",
    "tyv":"Википедия иштинден дилээр",
    "koi":"Кошшыны Википедия",
    "dsb":"Pśepytaś Wikipedija",
    "cbk":"Search Wikimedia Incubator",
    "lg":"Search Wikipedia",
    "dv":"ވިކިޕީޑިއާ އިން ހޯއްދަވާ",
    "ksh":"Söhke",
    "za":"Ra Wikipedia",
    "bxr":"Wikipedia сайтһаа бэдэрхэ",
    "blk":"ထိုမ်ႏထွား ဝီခီပီးဒီးယားကို",
    "gag":"Vikipediya içindä ara",
    "pfl":"Gugg",
    "szy":"kilim Wikipitiya",
    "haw":"Huli",
    "bew":"Cari Wikipédi",
    "pag":"Anapen Wikipedia",
    "tay":"Hhkangi’ Wikipidia",
    "pi":"Search Wikipedia",
    "zgh":"ⵔⵣⵓ ⴳ ⵡⵉⴽⵉⴱⵉⴷⵢⴰ",
    "awa":"विकिपीडिया मा खोजा जाय",
    "tcy":"ವಿಕಿಪೀಡಿಯನ್ ನಾಡ್‍ಲೆ",
    "inh":"Лаха Википеди чу",
    "krc":"Википедия изле",
    "xh":"Khangela i-Wikipedia",
    "atj":"Nantona Wikipetcia",
    "fon":"Bá kpɔn ɖo Wikipedya mɛ",
    "to":"Search Wikipedia",
    "pdc":"Uffgucke",
    "mnw":"ဂၠာဲ ဝဳကဳပဳဒဳယာ",
    "gpe":"Search Wikipedia",
    "arc":"ܒܨܝ",
    "shi":"",
    "tn":"Batla Wikipedia",
    "om":"Wikipedia barbaadi",
    "ki":"Search Wikipedia",
    "xal":"Wikipedia-с хәәх",
    "nia":"Alui Wikipedia",
    "jam":"Search Wikipidia",
    "kbp":"Ñɩnɩ Wikipediya taa",
    "wo":"Seet ci Wikipedia",
    "dga":"Bɔ Wikipiideɛ",
    "nov":"Search Wikipedia",
    "anp":"विकिपीडिया मँ खोजौ",
    "kbd":"Уикипедиэ къыщылъыхъуэн",
    "nqo":"ߊ߬ ߢߌߣߌ߲߫ ߥߞߌߔߘߋߞߎ ߞߣߐ߫",
    "bi":"Search Wikipedia",
    "rup":"Search Wikimedia Incubator",
    "tpi":"Painim long Wikipedia",
    "tet":"Buka iha Wikipedia",
    "kg":"Sosa Wikipedia",
    "guw":"Dín Wikipedia",
    "jbo":"sisku",
    "fj":"Search Wikipedia",
    "mad":"Sarè è Wikipedia",
    "lbe":"Луглан Википедия",
    "cu":"Википєдїꙗ : исканиѥ",
    "pcm":"Find-am for Wikipedia",
    "ty":"Rechercher sur Wikipedia",
    "kcg":"Zop Wikipedia",
    "trv":"Miying Wikipidiya",
    "sm":"Su&#039;e Wikipedia",
    "ami":"saoo’ Wikipedia",
    "srn":"Doorzoek Wikipedia",
    "btm":"Jalaki Wikipedia",
    "alt":"Википедия-ҥ бедреер",
    "ltg":"Meklēt Vikipedeja",
    "chr":"ᎠᏯᏍᏗ Wikipedia",
    "gcr":"Sasé annan Wikipédja",
    "ny":"Sakani Wikipedia",
    "dtp":"Ihumo Wikipedia",
    "st":"Batla Wikipedia",
    "kus":"Iem Wikipiidia",
    "ss":"Search Wikipedia",
    "ee":"Di Wikipedia",
    "gur":"Ɛ Wikipiidiya",
    "got":"Search Wikipedia",
    "ts":"Search Wikipedia",
    "bm":"Rechercher sur Wikipedia",
    "pih":"Search Wikipedia",
    "ve":"Search Wikipedia",
    "bbc":"Diori di bagasan Wikipedia",
    "rmy":"Căutare în Vikipidiya",
    "chy":"Search Tsétsêhéstâhese Wikipedia",
    "rn":"Rondeza Wikipedia",
    "fat":"Hwehwɛ Wikipedia",
    "ik":"Search Wikipedia",
    "igl":"Téné Wikipídiya",
    "guc":"Achajawaa sünain Wikipeetia",
    "ady":"Википедие-ым лъыхъу",
    "ch":"Aligao gi Wikipedia",
    "pnt":"Αράεμαν",
    "iu":"Search ᐅᐃᑭᐱᑎᐊ",
    "pwn":" qemulet/keminWikipedia",
    "din":"Yiɔ̈ɔ̈p Wikipedia",
    "sg":"Gi Wikipedia",
    "ti":"ኣብ ውሽጢ ዊኪፔዲያ ድለይ",
    "dz":"Wikipedia འཚོལ་ཞིབ་འབད།",
    "kl":"Ujarlerit",
    "bdr":"Memia Wikipidia",
    "cr":"Search Wikipedia"
    }